fullnameOverride: "wikijs"
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: wiki.cloudops-16.ucll.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wikijs-tls
      hosts:
        - wiki.cloudops-16.ucll.cloud

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
