apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pvc-access-binding
  namespace: kuma
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kuma
roleRef:
  kind: Role
  name: pvc-access
  apiGroup: rbac.authorization.k8s.io
